services:
  postgres-product:
    image: postgres:15
    container_name: postgres-product
    ports:
      - 5432:5432
    env_file:
      - configuration/docker/product/db/.env
      - configuration/docker/product/db/secret.env
    volumes:
      - ./data/postgres/product:/var/lib/postgresql/data
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio:/data
    env_file:
      - configuration/docker/minio/.env
      - configuration/docker/minio/secret.env
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    command: redis-server --save 60 1 --loglevel warning

  loki:
    image: grafana/loki:latest
    volumes:
      - ./configuration/docker/grafana/loki:/etc/loki
    command:
      - -config.file=/etc/loki/local-config.yaml
    networks:
      grafana-network:

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./logs:/var/log
      - ./configuration/docker/grafana/promtail:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
    networks:
      grafana-network:

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    networks:
      grafana-network:

networks:
  grafana-network:
    driver: bridge