spring:
  application:
    name: Gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: products
              uri: ${PRODUCT_SERVICE_URI}
              predicates:
                - Path=/products
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
server:
  port: 80